name: flutter_ntp
description: A small, fast NTP (Network Time Protocol) client for Flutter and Dart with built-in offset caching.
version: 0.1.0
homepage: https://github.com/mustafa-707/flutter_ntp
repository: https://github.com/mustafa-707/flutter_ntp
issue_tracker: https://github.com/mustafa-707/flutter_ntp/issues

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
